# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI with Xray cloud instance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BROWSER: firefox

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: generate auxiliary JSON for authenticating with Xray cloud and obtain token
      run: |
        echo token=$(curl -H "Content-Type: application/json" -X POST --data @"cloud_auth.json" ${{ secrets.XRAYCLOUD_BASE_URLÂ }}/api/v1/authenticate| tr -d '"') >> $GITHUB_ENV
    - name: Export scenarios from Xray using export_features_cloud.sh and generate .feature file(s)
      run: |
        yes | head -1 | ./export_features_cloud.sh || yes 
    - name: Cleanup old result files
      run: |
        ./run_cleanup.sh
    - name: Run Cypress tests and attach Cypress screenshots to Cucumber JSON report
      uses: cypress-io/github-action@v4
      continue-on-error: true
      with:
          install-command: npm install cypress@7.5.0 -D --legacy-peer-deps
          browser: ${{ env.BROWSER }}
    - name: Attach Screenshot evidence & merge feature test results in one file for upload to Jira XRay
      run: | 
        ./run_tests.sh || true
    - name: merge multiple Cucumber JSON reports to a single JSON file
      run: node_modules/cucumber-json-merge/bin/cucumber-json-merge  -d cypress/cucumber-json/
    - name: Import results to Xray using import_results_cloud.sh
      run: |
        ./import_results_cloud.sh || true